# Generated by Django 5.2.4 on 2025-11-14 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="room name", max_length=15)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invited"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("REMOVED", "Removed"),
                        ],
                        default="INVITED",
                        help_text="Current membership state",
                        max_length=12,
                    ),
                ),
                ("invited_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("accepted_on", models.DateTimeField(blank=True, null=True)),
                ("rejected_on", models.DateTimeField(blank=True, null=True)),
                ("removed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="room.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("created_by", "name"), name="unique_room_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="roommember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["INVITED", "ACCEPTED"])),
                fields=("room", "user", "status"),
                name="unique_active_membership",
            ),
        ),
    ]
