# Generated by Django 5.2.4 on 2026-04-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
